title       = "earthsearch"
baseURL     = "https://earthsearch-cli.tamnd.com/"
description = "A command line for earthsearch."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/earthsearch-cli"
